#!/bin/sh

# Change `style.css` or `style.min.css` to whatever you would like your compiled
# stylesheet to be called. Do not rename `style.scss` or alter references to it.

# No minification
#sass --watch style.scss:style.css --style expanded

/home/ulysse/.rvm/rubies/ruby-2.1.0/bin/sass --watch style.scss:../css/inuit.min.css --poll --style compressed --cache-location '/tmp'

exit 0
